name: Basic Setup Test

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package*.json'
      - '.eslintrc*'
      - 'tsconfig.json'

jobs:
  test-setup:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci --prefer-offline --no-audit
      
    - name: Run linter
      run: npm run lint -- --quiet --fix 